# Generated by Django 4.1.6 on 2023-03-08 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_alter_category_name_alter_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='newsapp.category', verbose_name='This is the help text'),
        ),
    ]
