# Generated by Django 4.1.6 on 2023-03-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_alter_category_name_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='Имя категории', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Имя категории', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en_us',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
